set_property PACKAGE_PIN D13 [get_ports sys_clk]
set_property PACKAGE_PIN R7 [get_ports SYNC_n]
set_property PACKAGE_PIN R8 [get_ports SDI]
set_property PACKAGE_PIN T7 [get_ports SCLK]
set_property PACKAGE_PIN M6 [get_ports rst_n]
set_property PACKAGE_PIN R6 [get_ports LDAC_n]
set_property IOSTANDARD LVCMOS33 [get_ports LDAC_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SDI]
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
create_clock -period 16 -name sys_clk -add [get_ports sys_clk]