webtalk_init -webtalk_dir /media/dylan/Data/work/git/RGA-PL/TLA2024/TLA2024/TLA2024.sim/sim_1/behav/xsim/xsim.dir/sim_tla2024_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Aug 11 15:39:36 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "63a3fe97-8874-477f-885a-9e3079d0af4a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f6e5458ce7a74c72b0e69d4a87228353" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "157" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2235.448 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "57189730 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "5.47_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "126184_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2037450097 -regid "" -xml /media/dylan/Data/work/git/RGA-PL/TLA2024/TLA2024/TLA2024.sim/sim_1/behav/xsim/xsim.dir/sim_tla2024_behav/webtalk/usage_statistics_ext_xsim.xml -html /media/dylan/Data/work/git/RGA-PL/TLA2024/TLA2024/TLA2024.sim/sim_1/behav/xsim/xsim.dir/sim_tla2024_behav/webtalk/usage_statistics_ext_xsim.html -wdm /media/dylan/Data/work/git/RGA-PL/TLA2024/TLA2024/TLA2024.sim/sim_1/behav/xsim/xsim.dir/sim_tla2024_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
